#!/usr/bin/env python3

import atexit
import sys
import time
from stepper import Stepper

MIDPOINT_X = 20000
MIDPOINT_Y = 20000

class PictureScan(object):
    def __init__(self):
        self.steppers = [
            CalibratedStepper(0, power = 127),
            CalibratedStepper(1, power = 127),
        ]

        self.current_pos = [0, 0]

    def get_current(self):
        return 0.0

    def go(self, axis, steps):
        self.steppers[axis].go(steps)
        self.coords[axis] += steps

    def capture(self):
        pass

    def acquire(self):
        print("Beginning acquisition")
        for iy in range(10):

            for ix in range(20):
                self.go(0, 40000/20)
                self.capture()

            self.go(1, 40000/20)

            for ix in range(20):
                self.go(0, -40000/20)
                self.capture()

            self.go(1, 40000/20)

    def start():
        self.acquire()

if __name__ == "__main__":
    PictureScan().start()
