#!/usr/bin/env python3

import atexit
import sys
from camera.calibrated_stepper import CalibratedStepper

if __name__ == "__main__":
    axis = int(sys.argv[1])
    s = CalibratedStepper(axis, power = 127)
    atexit.register(lambda: s.off())
    s.goto(int(sys.argv[2]))

